#proxy_url: "http://127.0.0.1:10809"
base_url: "https://api.openai.com/v1"
openai_api_key: "sk-key"
temperature: 0.2
telegram_token: "tg-token"
allowed_telegram_usernames: ["tom","tony","lisa"]
free_chat_count: 10



